go desy <number_small>: user.desktop(number_small)
go desy right: user.desktop_next()
go desy left: user.desktop_last()
desy show: user.desktop_show()
window move desy <number>: user.window_move_desktop(number)
window move desy left: user.window_move_desktop_left()
window move desy right: user.window_move_desktop_right()
